# Simple workflow for deploying static content to GitHub Pages
name: Deploy demo page to gh-pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node build
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          npm ci --foreground-scripts
          npm run build
          ls -la ./
          ls -laR ./build
          ls -laR ./demo
          ls -laR ./json
          ls -laR ./docs
          mkdir build-demo
          cp README.md ./build-demo/
          cp -r ./build ./build-demo/
          cp -r ./demo ./build-demo/
          cp -r ./json ./build-demo/
          cp -r ./docs ./build-demo/
          cp ./voices.schema.json ./build-demo/
          ls -laR ./build-demo


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from develop,
        # also change the `main` in `refs/heads/develop`
        # below accordingly.
        if: github.ref == 'refs/heads/develop'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build-demo
          publish_branch: gh-pages # default: gh-pages
          destination_dir: ./
          enable_jekyll: true # yes for markdown files